"""Build the ONE-SHOT COMMON-DATA overlay (common-data-stage.tar).

Why a *class*-level overlay, not a per-app one
----------------------------------------------
The §5-E deb-closure (``tools/deb_closure.py``) follows ``DT_NEEDED`` only, so it
ships the shared libraries an app links but DROPS everything an app reads at run
time that is NOT an ELF dependency: the TLS root store, the freedesktop MIME
database, the icon-theme indices GTK probes, ``/etc/machine-id``, a usable
``$DBUS_SESSION_BUS_ADDRESS``, the compiled ``C.UTF-8`` locale. Each missing piece
shows up per-app as its own failure ("missing CA / no file types / icon lookup
stall / dbus connect refused / SIGABRT in setlocale"). Rather than patch each app,
this builder assembles ONE overlay that unblocks the data those failures share —
so a whole CLASS of GUI + network glibc apps gets what it needs in a single stage
tar.

Groups (each independently selectable; ``--all`` = every group)
---------------------------------------------------------------
``ca``        ``/etc/ssl/certs/ca-certificates.crt`` — the Mozilla CA trust bundle
              assembled from the noble ``ca-certificates`` .deb (its postinst would
              run ``update-ca-certificates``; we reproduce the default = concat all
              enabled mozilla PEMs, sorted, each newline-terminated). Unblocks TLS
              verification for chromium / curl / openssl / wget / git / python-ssl.

``mime``      ``/usr/share/mime/**`` — the freedesktop shared MIME database. The
              ``shared-mime-info`` .deb ships ONLY the source
              ``packages/freedesktop.org.xml``; the binary database
              (``mime.cache`` + ``globs2`` + ``magic`` + ``aliases`` + …) that GIO /
              GTK / Qt actually read is generated by the package's postinst via
              ``update-mime-database``. We run that host-side over the shipped XML so
              the overlay carries the COMPILED database, not just the source. Without
              it, file-type detection (``g_content_type_guess``) returns
              octet-stream for everything and "Open With" / drag-drop break.

``icons``     ``/usr/share/icons/hicolor/index.theme`` +
              ``/usr/share/icons/Adwaita/index.theme`` (+ the Adwaita theme payload).
              The ``index.theme`` is the load-bearing file: without it GTK does not
              recognise the theme AT ALL and every ``gtk_icon_theme_lookup`` misses
              (apps draw blank buttons / stall retrying the lookup). NOTE the binary
              ``icon-theme.cache`` is postinst-generated by ``gtk-update-icon-cache``
              (NOT on this host) — GTK falls back to a directory scan without it, so
              we ship the indices + payload and HONESTLY omit the binary cache (a
              perf optimisation, not a correctness gate). See HONEST SCOPE.

``machine-id````/etc/machine-id`` + ``/var/lib/dbus/machine-id`` + a session-bus
              ``/etc/dbus-1/session.conf`` stub. Many GTK/GLib apps call
              ``g_dbus_*`` / read the D-Bus machine-id at startup; a missing
              machine-id makes libdbus abort ("Unable to load
              /var/lib/dbus/machine-id"). We ship a fixed, syntactically-valid
              32-hex id (a STUB — no real per-device identity needed for a
              single-user app sandbox) so the read succeeds and the app proceeds.

``locale``    ``/usr/lib/locale/C.utf8/**`` — the COMPILED ``C.UTF-8`` locale pulled
              straight from the noble ``libc-bin`` .deb (it ships the prebuilt
              locale, unlike the source-only ``locales`` package). The base rootfs
              has NO compiled locales; an app that does ``setlocale(LC_ALL,
              "C.UTF-8")`` (most GTK apps via ``gtk_init``) then SIGABRTs. Shipping
              this 0.4 MB tree fixes that for the whole UTF-8 class. (Matches the
              WS-4 C.UTF-8 finding; staged here so it travels with the other common
              data.)

What this overlay deliberately does NOT do
------------------------------------------
* It does not weaken any sandbox or emulate a kernel-denied syscall — every member
  is a plain rootfs data file the app reads.
* It does not ship shared libraries (those are the §5-E lib closure's job); the
  only ``usr/lib`` content is the ``locale/C.utf8`` data tree.
* It is base-additive: it writes config/data paths the base rootfs lacks and never
  repoints a base SONAME (validated against ``stage_tar_spec`` — conformant).

HONEST SCOPE
------------
HOST-ONLY. ``--list`` is a network-only dry run (resolves each group's .deb
Filename, prints the planned members) and never downloads/packs. A full ``--out``
build is a NETWORK path (fetches the four data .debs). The on-device effect (apps
finding CA roots / MIME types / icons / machine-id / locale) is the
integration/device gate — the main session stages the produced tar. The
``mime.cache`` is generated by THIS host's ``update-mime-database`` if present;
when it is absent the ``mime`` group degrades to shipping the source XML only and
SAYS SO (``mime_compiled=False`` in the result) rather than silently shipping a
half database. The Adwaita/hicolor ``icon-theme.cache`` is NOT shipped (no
``gtk-update-icon-cache`` here) — GTK works without it. All offline-testable logic
(bundle assembly, tar shape, group selection) is covered by ``--selftest`` and the
pytest.
"""

from __future__ import annotations

import argparse
import io
import json
import shutil
import subprocess
import tarfile
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from tools.deb_closure import (
    _download_deb,
    fetch_packages_index,
    parse_packages,
)
from tools.build_apt_dpkg_overlay import _decompress_data_tar

# --------------------------------------------------------------------------- #
# Constants — noble (Ubuntu) ports mirror; the ALR base is Ubuntu noble 24.04.
# --------------------------------------------------------------------------- #

MIRROR = "http://ports.ubuntu.com/ubuntu-ports"
SUITE = "noble"
ARCH = "arm64"
# ca-certificates + shared-mime-info + adwaita/hicolor + libc-bin all live in main.
COMPONENTS = ("main",)

# Group -> the noble source package whose .deb supplies that group's data.
GROUP_PACKAGES: dict[str, str] = {
    "ca": "ca-certificates",
    "mime": "shared-mime-info",
    "icons": "adwaita-icon-theme",      # hicolor pulled too (see ICON_PACKAGES)
    "locale": "libc-bin",
    # "machine-id" is synthesized, no .deb.
}
# icons needs BOTH the Adwaita theme and the hicolor base theme index.
ICON_PACKAGES = ("hicolor-icon-theme", "adwaita-icon-theme")

ALL_GROUPS = ("ca", "mime", "icons", "machine-id", "locale")

# --- ca group -------------------------------------------------------------- #
CA_SRC_PREFIX = "usr/share/ca-certificates/"
CA_BUNDLE_PATH = "etc/ssl/certs/ca-certificates.crt"

# --- mime group ------------------------------------------------------------ #
MIME_DIR = "usr/share/mime"
MIME_SRC_XML = "usr/share/mime/packages/freedesktop.org.xml"

# --- icons group ----------------------------------------------------------- #
ICON_DIR = "usr/share/icons"
HICOLOR_INDEX = "usr/share/icons/hicolor/index.theme"
ADWAITA_INDEX = "usr/share/icons/Adwaita/index.theme"

# --- machine-id group ------------------------------------------------------ #
# A fixed, syntactically valid machine-id (32 lowercase hex). STUB identity — a
# single-user app sandbox needs the read to succeed, not a real device id.
STUB_MACHINE_ID = "a1b2c3d4e5f60718293a4b5c6d7e8f90"
MACHINE_ID_PATHS = ("etc/machine-id", "var/lib/dbus/machine-id")
DBUS_SESSION_CONF_PATH = "etc/dbus-1/session.conf"
# Minimal session-bus config: a unix-abstract session bus address + the default
# servicedirs. Enough for libdbus to parse and for g_dbus to find a session bus
# address (apps that just need the machine-id read won't even open the socket).
DBUS_SESSION_CONF_BODY = (
    '<?xml version="1.0"?>\n'
    '<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"\n'
    ' "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">\n'
    "<!-- ALR common-data overlay: minimal session-bus stub. -->\n"
    "<busconfig>\n"
    "  <type>session</type>\n"
    "  <listen>unix:tmpdir=/tmp</listen>\n"
    "  <standard_session_servicedirs />\n"
    "  <policy context=\"default\">\n"
    "    <allow send_destination=\"*\" eavesdrop=\"true\"/>\n"
    "    <allow eavesdrop=\"true\"/>\n"
    "    <allow own=\"*\"/>\n"
    "  </policy>\n"
    "</busconfig>\n"
)

# --- locale group ---------------------------------------------------------- #
LOCALE_PREFIX = "usr/lib/locale/C.utf8/"


# --------------------------------------------------------------------------- #
# Result
# --------------------------------------------------------------------------- #

@dataclass
class CommonDataResult:
    out_tar: str
    groups: tuple[str, ...] = ()
    members: tuple[str, ...] = ()
    file_count: int = 0
    ca_cert_count: int = 0
    ca_bundle_bytes: int = 0
    mime_file_count: int = 0
    mime_compiled: bool = False           # did update-mime-database run?
    icon_file_count: int = 0
    icon_cache_shipped: bool = False      # binary icon-theme.cache (postinst tool)
    locale_file_count: int = 0
    debs: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()

    def as_dict(self) -> dict:
        return {
            "out_tar": self.out_tar,
            "groups": list(self.groups),
            "members": list(self.members),
            "file_count": self.file_count,
            "ca_cert_count": self.ca_cert_count,
            "ca_bundle_bytes": self.ca_bundle_bytes,
            "ca_bundle_kib": round(self.ca_bundle_bytes / 1024, 1),
            "mime_file_count": self.mime_file_count,
            "mime_compiled": self.mime_compiled,
            "icon_file_count": self.icon_file_count,
            "icon_cache_shipped": self.icon_cache_shipped,
            "locale_file_count": self.locale_file_count,
            "debs": list(self.debs),
            "notes": list(self.notes),
        }


# --------------------------------------------------------------------------- #
# tar helpers (§5-E ./-rooted, mtime=0, deterministic)
# --------------------------------------------------------------------------- #

def _member_name(rel: str) -> str:
    return "./" + rel.strip("/")


def _add_dir(tar: tarfile.TarFile, rel: str, mode: int = 0o755) -> None:
    ti = tarfile.TarInfo(_member_name(rel))
    ti.type = tarfile.DIRTYPE
    ti.mode = mode
    ti.mtime = 0
    tar.addfile(ti)


def _add_file(tar: tarfile.TarFile, rel: str, data: bytes, mode: int = 0o644) -> None:
    ti = tarfile.TarInfo(_member_name(rel))
    ti.size = len(data)
    ti.mode = mode
    ti.mtime = 0
    ti.type = tarfile.REGTYPE
    tar.addfile(ti, io.BytesIO(data))


def _norm(rel: str) -> str:
    """Strip leading ./ and / from a tar member name -> rootfs-relative path."""
    while rel.startswith("./"):
        rel = rel[2:]
    return rel.lstrip("/")


# --------------------------------------------------------------------------- #
# Filename resolution
# --------------------------------------------------------------------------- #

def resolve_filenames(
    packages,
    *,
    mirror: str = MIRROR,
    suite: str = SUITE,
    arch: str = ARCH,
    components=COMPONENTS,
    index: dict[str, dict] | None = None,
) -> dict[str, str]:
    """Resolve each package name to its .deb ``Filename`` in the noble index.

    NETWORK unless ``index`` is supplied (offline/selftest). Raises if a requested
    package is absent from the index."""
    if index is None:
        index = parse_packages(
            fetch_packages_index(mirror, suite, arch, components=components)
        )
    out: dict[str, str] = {}
    for pkg in packages:
        fields = index.get(pkg, {})
        filename = fields.get("Filename")
        if not filename:
            raise RuntimeError(
                f"{pkg} not found in {suite}/{'+'.join(components)} index"
            )
        out[pkg] = filename
    return out


def packages_for_groups(groups) -> list[str]:
    """The set of noble packages a group selection needs (deduped, ordered)."""
    pkgs: list[str] = []
    for g in groups:
        if g == "icons":
            for p in ICON_PACKAGES:
                if p not in pkgs:
                    pkgs.append(p)
        elif g in GROUP_PACKAGES:
            p = GROUP_PACKAGES[g]
            if p not in pkgs:
                pkgs.append(p)
        # machine-id needs no package
    return pkgs


# --------------------------------------------------------------------------- #
# ca group — assemble the CA bundle from the ca-certificates .deb
# --------------------------------------------------------------------------- #

def assemble_ca_bundle(deb: Path) -> tuple[bytes, int]:
    """Concatenate every PEM CA in the ca-certificates .deb into one bundle.

    Reproduces ``update-ca-certificates`` with the default (all-enabled) config:
    pulls every ``usr/share/ca-certificates/**/*.crt`` regular-file member from the
    .deb data.tar (in-memory; tolerant of absolute-symlink members elsewhere),
    keeps only PEM-bearing files, and concatenates them sorted-by-path
    (deterministic), each cert newline-terminated. Returns ``(bundle, cert_count)``.
    """
    raw = _decompress_data_tar(deb)
    pems: list[tuple[str, bytes]] = []
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as t:
        for m in t.getmembers():
            rel = _norm(m.name)
            if rel.startswith(CA_SRC_PREFIX) and rel.endswith(".crt") and m.isfile():
                fh = t.extractfile(m)
                if fh is None:
                    continue
                body = fh.read()
                if b"-----BEGIN CERTIFICATE-----" not in body:
                    continue
                pems.append((rel, body))
    pems.sort(key=lambda kv: kv[0])
    chunks = [b if b.endswith(b"\n") else b + b"\n" for _, b in pems]
    return b"".join(chunks), len(pems)


# --------------------------------------------------------------------------- #
# mime group — extract the source XML, compile via update-mime-database
# --------------------------------------------------------------------------- #

def _extract_prefix(deb: Path, prefix: str, dest_root: Path) -> list[str]:
    """Extract every regular-file member under ``prefix`` of a .deb to dest_root.

    In-memory data.tar read (no extract-to-disk for the whole archive, so an
    absolute-symlink member elsewhere can't abort us). Returns the sorted list of
    rootfs-relative paths written. ``prefix`` is matched on the normalised
    (leading-./-stripped) member name."""
    raw = _decompress_data_tar(deb)
    written: list[str] = []
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as t:
        for m in t.getmembers():
            rel = _norm(m.name)
            if not rel.startswith(prefix) or not m.isfile():
                continue
            fh = t.extractfile(m)
            if fh is None:
                continue
            dst = dest_root / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(fh.read())
            written.append(rel)
    written.sort()
    return written


def build_mime_tree(deb: Path, work: Path) -> tuple[Path, bool, list[str]]:
    """Stage the source MIME XML, then compile the binary database if possible.

    Returns ``(mime_root, compiled, notes)`` where ``mime_root`` is the directory
    whose ``usr/share/mime`` subtree should be packed. ``compiled`` is True iff
    ``update-mime-database`` ran (and thus ``mime.cache``/``globs2``/``magic``/…
    were generated); when the tool is absent only the source XML is staged and a
    note explains the degradation."""
    notes: list[str] = []
    _extract_prefix(deb, MIME_DIR + "/", work)
    mime_share = work / MIME_DIR
    tool = shutil.which("update-mime-database")
    compiled = False
    if tool is not None and mime_share.is_dir():
        try:
            subprocess.run(
                [tool, str(mime_share)],
                check=True, capture_output=True,
            )
            compiled = (mime_share / "mime.cache").is_file()
        except subprocess.CalledProcessError as exc:  # pragma: no cover - host tool
            notes.append(
                f"update-mime-database failed (rc={exc.returncode}); shipping source "
                "XML only — file-type detection will be degraded on device"
            )
        if not compiled and not notes:
            notes.append(
                "update-mime-database ran but produced no mime.cache; shipping source "
                "XML only"
            )
    else:
        notes.append(
            "update-mime-database not on PATH; mime group ships the source XML only "
            "(no compiled mime.cache/globs2/magic) — run the builder on a host with "
            "shared-mime-info installed, or compile on device"
        )
    return work, compiled, notes


# --------------------------------------------------------------------------- #
# icons group — index.theme (+ Adwaita payload) from the theme .debs
# --------------------------------------------------------------------------- #

def _pack_deb_prefix(
    tar: tarfile.TarFile, deb: Path, prefix: str, *, skip=()
) -> list[str]:
    """Copy every regular-file member of ``deb`` under ``prefix`` into ``tar`` at
    its rootfs-absolute (./-rooted) path, preserving mode bits. ``skip`` is an
    iterable of member-name SUFFIXES to drop (e.g. a postinst-only cache). Returns
    the sorted rootfs-relative paths packed."""
    raw = _decompress_data_tar(deb)
    packed: list[str] = []
    skip = tuple(skip)
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as t:
        for m in t.getmembers():
            rel = _norm(m.name)
            if not rel.startswith(prefix) or not m.isfile():
                continue
            if skip and rel.endswith(skip):
                continue
            fh = t.extractfile(m)
            if fh is None:
                continue
            data = fh.read()
            mode = (m.mode & 0o7777) or 0o644
            _add_file(tar, rel, data, mode=mode)
            packed.append(rel)
    packed.sort()
    return packed


# --------------------------------------------------------------------------- #
# Full build
# --------------------------------------------------------------------------- #

def build_common_data_overlay(
    out_tar: str | Path,
    groups,
    *,
    mirror: str = MIRROR,
    suite: str = SUITE,
    arch: str = ARCH,
    components=COMPONENTS,
    cache_dir: str | Path | None = None,
    index: dict[str, dict] | None = None,
    # offline/selftest injection: skip the network for the ca group.
    ca_bundle: bytes | None = None,
    ca_cert_count: int | None = None,
) -> CommonDataResult:
    """Pack the selected groups into one §5-E ``common-data-stage.tar``.

    NETWORK PATH unless every selected group's data is injected. Resolves each
    group's noble .deb, assembles/extracts/synthesizes its data, and writes it at
    the canonical rootfs-absolute paths. ``machine-id`` is synthesized (no deb).
    """
    groups = tuple(dict.fromkeys(groups))  # dedupe, keep order
    unknown = [g for g in groups if g not in ALL_GROUPS]
    if unknown:
        raise ValueError(f"unknown group(s): {unknown}; choose from {ALL_GROUPS}")

    out_tar = Path(out_tar)
    out_tar.parent.mkdir(parents=True, exist_ok=True)
    cache = Path(cache_dir) if cache_dir is not None else Path("/tmp/deb-cache-ubuntu")

    # Resolve the .deb Filenames we will need (skip when fully injected offline).
    need_net = not (set(groups) <= {"machine-id"} or
                    (set(groups) <= {"ca", "machine-id"} and ca_bundle is not None))
    filenames: dict[str, str] = {}
    if need_net or (("ca" in groups) and ca_bundle is None):
        filenames = resolve_filenames(
            packages_for_groups(groups),
            mirror=mirror, suite=suite, arch=arch, components=components, index=index,
        )

    members: list[str] = []
    debs: list[str] = []
    notes: list[str] = []
    res = CommonDataResult(out_tar=str(out_tar), groups=groups)

    # A scratch dir for the mime compile step (cleaned at the end).
    work = Path(tempfile.mkdtemp(prefix="alr-common-data-"))
    try:
        with tarfile.open(out_tar, "w") as tar:
            # --- ca ------------------------------------------------------- #
            if "ca" in groups:
                if ca_bundle is None:
                    fn = filenames["ca-certificates"]
                    deb = _download_deb(mirror, fn, cache)
                    debs.append(Path(fn).name)
                    ca_bundle, ca_cert_count = assemble_ca_bundle(deb)
                elif ca_cert_count is None:
                    ca_cert_count = ca_bundle.count(b"-----BEGIN CERTIFICATE-----")
                for d in ("etc", "etc/ssl", "etc/ssl/certs"):
                    _add_dir(tar, d)
                _add_file(tar, CA_BUNDLE_PATH, ca_bundle)
                members.append("./" + CA_BUNDLE_PATH)
                res.ca_cert_count = ca_cert_count or 0
                res.ca_bundle_bytes = len(ca_bundle)

            # --- mime ----------------------------------------------------- #
            if "mime" in groups:
                fn = filenames["shared-mime-info"]
                deb = _download_deb(mirror, fn, cache)
                debs.append(Path(fn).name)
                mime_root, compiled, mnotes = build_mime_tree(deb, work)
                notes.extend(mnotes)
                res.mime_compiled = compiled
                mime_share = mime_root / MIME_DIR
                count = 0
                for p in sorted(mime_share.rglob("*")):
                    if p.is_file():
                        rel = p.relative_to(mime_root).as_posix()
                        _add_file(tar, rel, p.read_bytes())
                        members.append("./" + rel)
                        count += 1
                res.mime_file_count = count

            # --- icons ---------------------------------------------------- #
            if "icons" in groups:
                count = 0
                # hicolor: just the base index.theme (it has no icons of its own).
                fn = filenames["hicolor-icon-theme"]
                deb = _download_deb(mirror, fn, cache)
                debs.append(Path(fn).name)
                packed = _pack_deb_prefix(
                    tar, deb, "usr/share/icons/hicolor/index.theme"
                )
                members += ["./" + p for p in packed]
                count += len(packed)
                # Adwaita: the full theme payload + index, MINUS the postinst-only
                # binary icon-theme.cache (no gtk-update-icon-cache here).
                fn = filenames["adwaita-icon-theme"]
                deb = _download_deb(mirror, fn, cache)
                debs.append(Path(fn).name)
                packed = _pack_deb_prefix(
                    tar, deb, "usr/share/icons/Adwaita/",
                    skip=("icon-theme.cache",),
                )
                members += ["./" + p for p in packed]
                count += len(packed)
                res.icon_file_count = count
                res.icon_cache_shipped = False
                notes.append(
                    "icons: shipped index.theme + Adwaita payload; binary "
                    "icon-theme.cache omitted (gtk-update-icon-cache not on host) — "
                    "GTK falls back to a directory scan, lookups still resolve"
                )

            # --- machine-id ---------------------------------------------- #
            if "machine-id" in groups:
                _add_dir(tar, "etc")
                _add_dir(tar, "var")
                _add_dir(tar, "var/lib")
                _add_dir(tar, "var/lib/dbus")
                _add_dir(tar, "etc/dbus-1")
                for p in MACHINE_ID_PATHS:
                    _add_file(tar, p, (STUB_MACHINE_ID + "\n").encode())
                    members.append("./" + p)
                _add_file(tar, DBUS_SESSION_CONF_PATH,
                          DBUS_SESSION_CONF_BODY.encode())
                members.append("./" + DBUS_SESSION_CONF_PATH)

            # --- locale --------------------------------------------------- #
            if "locale" in groups:
                fn = filenames["libc-bin"]
                deb = _download_deb(mirror, fn, cache)
                debs.append(Path(fn).name)
                packed = _pack_deb_prefix(tar, deb, LOCALE_PREFIX)
                members += ["./" + p for p in packed]
                res.locale_file_count = len(packed)

        with tarfile.open(out_tar, "r") as t:
            res.file_count = sum(1 for m in t.getmembers() if m.isfile())
    finally:
        shutil.rmtree(work, ignore_errors=True)

    res.members = tuple(sorted(set(members)))
    res.debs = tuple(dict.fromkeys(debs))
    res.notes = tuple(notes)
    return res


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _selected_groups(args) -> tuple[str, ...]:
    if args.all:
        return ALL_GROUPS
    sel = [g for g in ALL_GROUPS if getattr(args, g.replace("-", "_"))]
    return tuple(sel)


def _plan(groups, *, mirror, suite, components, index=None) -> dict:
    """Resolve filenames + the planned member paths for ``groups`` (the --list view)."""
    pkgs = packages_for_groups(groups)
    filenames = resolve_filenames(
        pkgs, mirror=mirror, suite=suite, arch=ARCH, components=components, index=index
    ) if pkgs else {}
    planned: list[str] = []
    if "ca" in groups:
        planned.append("./" + CA_BUNDLE_PATH)
    if "mime" in groups:
        planned.append("./" + MIME_DIR + "/** (compiled via update-mime-database)")
    if "icons" in groups:
        planned += ["./" + HICOLOR_INDEX, "./" + ADWAITA_INDEX,
                    "./" + ICON_DIR + "/Adwaita/** (minus icon-theme.cache)"]
    if "machine-id" in groups:
        planned += ["./" + p for p in MACHINE_ID_PATHS] + ["./" + DBUS_SESSION_CONF_PATH]
    if "locale" in groups:
        planned.append("./" + LOCALE_PREFIX + "**")
    return {
        "groups": list(groups),
        "packages": pkgs,
        "filenames": filenames,
        "planned_members": planned,
        "update_mime_database": shutil.which("update-mime-database") or "(absent)",
        "gtk_update_icon_cache": shutil.which("gtk-update-icon-cache") or "(absent)",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="build_common_data_overlay",
        description="Build the one-shot COMMON-DATA overlay (CA bundle + MIME db + "
        "icon indices + machine-id/dbus stub + C.UTF-8 locale) that most GUI+network "
        "glibc apps need but the DT_NEEDED-only deb closure drops.",
    )
    parser.add_argument("--out", help="output stage tar (e.g. /tmp/common-data-stage.tar)")
    # per-group flags
    parser.add_argument("--ca", action="store_true",
                        help="ship /etc/ssl/certs/ca-certificates.crt (Mozilla CA bundle)")
    parser.add_argument("--mime", action="store_true",
                        help="ship /usr/share/mime/** (freedesktop MIME db, compiled)")
    parser.add_argument("--icons", action="store_true",
                        help="ship hicolor + Adwaita index.theme (+ Adwaita payload)")
    parser.add_argument("--machine-id", dest="machine_id", action="store_true",
                        help="ship /etc/machine-id + dbus machine-id + session.conf stub")
    parser.add_argument("--locale", action="store_true",
                        help="ship /usr/lib/locale/C.utf8/** (compiled C.UTF-8 locale)")
    parser.add_argument("--all", action="store_true", help="select every group")
    parser.add_argument("--suite", default=SUITE)
    parser.add_argument("--mirror", default=MIRROR)
    parser.add_argument("--component", action="append", dest="components",
                        help="repo component (repeatable; default main)")
    parser.add_argument("--cache", default="/tmp/deb-cache-ubuntu")
    parser.add_argument("--list", "--dry-run", action="store_true", dest="dry_run",
                        help="resolve each group's .deb + print the planned members "
                        "WITHOUT downloading/packing")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args(argv)

    if args.selftest:
        return _selftest()

    components = tuple(args.components) if args.components else COMPONENTS
    groups = _selected_groups(args)
    if not groups:
        # Sensible default for --list with no group flags: show everything.
        groups = ALL_GROUPS

    if args.dry_run:
        info = _plan(groups, mirror=args.mirror, suite=args.suite,
                     components=components)
        if args.json:
            print(json.dumps(info, indent=2))
        else:
            print(f"common-data overlay plan ({args.suite}/{'+'.join(components)}):")
            print(f"  groups: {', '.join(info['groups'])}")
            for pkg in info["packages"]:
                print(f"  deb {pkg}: {info['filenames'].get(pkg)}")
            print(f"  update-mime-database: {info['update_mime_database']}")
            print(f"  gtk-update-icon-cache: {info['gtk_update_icon_cache']}")
            print("  planned members:")
            for m in info["planned_members"]:
                print(f"    {m}")
        return 0

    if not args.out:
        parser.error("--out is required for a full build (or use --list / --selftest)")

    res = build_common_data_overlay(
        args.out, groups, mirror=args.mirror, suite=args.suite, arch=ARCH,
        components=components, cache_dir=args.cache,
    )
    if args.json:
        print(json.dumps(res.as_dict(), indent=2))
    else:
        print(f"built {res.out_tar}")
        print(f"  groups: {', '.join(res.groups)}")
        print(f"  files in overlay: {res.file_count}")
        if "ca" in res.groups:
            print(f"  CA bundle: {res.ca_cert_count} certs, "
                  f"{round(res.ca_bundle_bytes / 1024, 1)} KiB")
        if "mime" in res.groups:
            print(f"  MIME db: {res.mime_file_count} files "
                  f"(compiled={res.mime_compiled})")
        if "icons" in res.groups:
            print(f"  icons: {res.icon_file_count} files "
                  f"(binary cache shipped={res.icon_cache_shipped})")
        if "locale" in res.groups:
            print(f"  locale C.utf8: {res.locale_file_count} files")
        if res.debs:
            print(f"  source debs: {', '.join(res.debs)}")
        if res.notes:
            print("  notes:")
            for n in res.notes:
                print(f"    - {n}")
    return 0


# --------------------------------------------------------------------------- #
# Selftest (OFFLINE — synthetic debs / injected CA bundle)
# --------------------------------------------------------------------------- #

def _make_synthetic_deb(tmp: Path, name: str, files: dict[str, bytes]) -> Path:
    """Build a minimal .deb (ar archive, uncompressed data.tar) for offline tests.

    Returns the .deb path or raises if ``ar`` is unavailable."""
    data_tar = tmp / "data.tar"
    with tarfile.open(data_tar, "w") as dt:
        for rel, body in files.items():
            ti = tarfile.TarInfo("./" + rel)
            ti.size = len(body)
            ti.mode = 0o644
            dt.addfile(ti, io.BytesIO(body))
    (tmp / "debian-binary").write_text("2.0\n")
    (tmp / "control.tar").write_bytes(b"")
    deb = tmp / name
    subprocess.run(
        ["ar", "qcS", deb.name, "debian-binary", "control.tar", "data.tar"],
        check=True, capture_output=True, cwd=str(tmp),
    )
    return deb


def _selftest() -> int:
    failures = 0

    def check(label: str, cond: bool) -> None:
        nonlocal failures
        if not cond:
            failures += 1
        print(f"  [{'PASS' if cond else 'FAIL'}] {label}")

    # --- group/package selection logic (pure) ------------------------------ #
    check("packages_for_groups(ca)=ca-certificates",
          packages_for_groups(["ca"]) == ["ca-certificates"])
    check("packages_for_groups(icons) pulls hicolor+adwaita",
          packages_for_groups(["icons"]) == ["hicolor-icon-theme", "adwaita-icon-theme"])
    check("packages_for_groups(machine-id) needs no deb",
          packages_for_groups(["machine-id"]) == [])
    check("packages_for_groups dedupes across groups",
          packages_for_groups(["ca", "ca"]) == ["ca-certificates"])
    check("ALL_GROUPS has the 5 documented groups",
          set(ALL_GROUPS) == {"ca", "mime", "icons", "machine-id", "locale"})

    # --- machine-id only (no network, no ar) ------------------------------- #
    with tempfile.TemporaryDirectory() as t:
        out = Path(t) / "mid.tar"
        res = build_common_data_overlay(out, ["machine-id"])
        with tarfile.open(out) as tar:
            names = {m.name: m for m in tar.getmembers()}
            bodies = {n: tar.extractfile(m).read()
                      for n, m in names.items() if m.isfile()}
        check("machine-id overlay ships ./etc/machine-id",
              "./etc/machine-id" in names)
        check("machine-id overlay ships ./var/lib/dbus/machine-id",
              "./var/lib/dbus/machine-id" in names)
        check("machine-id overlay ships ./etc/dbus-1/session.conf",
              "./etc/dbus-1/session.conf" in names)
        check("machine-id is 32-hex + newline",
              bodies.get("./etc/machine-id", b"").strip() == STUB_MACHINE_ID.encode()
              and len(STUB_MACHINE_ID) == 32)
        check("dbus session.conf is valid-ish XML busconfig",
              b"<busconfig>" in bodies.get("./etc/dbus-1/session.conf", b""))
        check("machine-id build needs no deb", res.debs == ())
        check("all members ./-rooted", all(n.startswith("./") for n in names))

    # --- ca group via injected bundle (no network) ------------------------- #
    fake = (b"-----BEGIN CERTIFICATE-----\nMIIBfake\n-----END CERTIFICATE-----\n")
    bundle = fake * 3
    with tempfile.TemporaryDirectory() as t:
        out = Path(t) / "ca.tar"
        res = build_common_data_overlay(out, ["ca"], ca_bundle=bundle)
        with tarfile.open(out) as tar:
            names = {m.name: m for m in tar.getmembers()}
            body = tar.extractfile("./" + CA_BUNDLE_PATH).read()
        check("ca overlay ships ./etc/ssl/certs/ca-certificates.crt",
              "./" + CA_BUNDLE_PATH in names)
        check("ca bundle == injected bytes", body == bundle)
        check("ca cert_count counted from injected bundle (3)",
              res.ca_cert_count == 3)

    # --- ca + machine-id combined (injected ca, no network) ---------------- #
    with tempfile.TemporaryDirectory() as t:
        out = Path(t) / "combo.tar"
        res = build_common_data_overlay(
            out, ["ca", "machine-id"], ca_bundle=bundle, ca_cert_count=3)
        with tarfile.open(out) as tar:
            names = {m.name for m in tar.getmembers()}
        check("combo overlay has both ca bundle and machine-id",
              "./" + CA_BUNDLE_PATH in names and "./etc/machine-id" in names)
        check("combo groups recorded in order", res.groups == ("ca", "machine-id"))

    # --- unknown group rejected -------------------------------------------- #
    try:
        with tempfile.TemporaryDirectory() as t:
            build_common_data_overlay(Path(t) / "x.tar", ["nope"])
        check("unknown group rejected", False)
    except ValueError:
        check("unknown group rejected", True)

    # --- assemble_ca_bundle over a synthetic ca-certificates-like .deb ------ #
    if shutil.which("ar"):
        with tempfile.TemporaryDirectory() as t:
            tmp = Path(t)
            deb = _make_synthetic_deb(tmp, "synthetic-cacerts.deb", {
                "usr/share/ca-certificates/mozilla/A.crt":
                    b"-----BEGIN CERTIFICATE-----\nAAAA\n-----END CERTIFICATE-----\n",
                "usr/share/ca-certificates/mozilla/B.crt":
                    b"-----BEGIN CERTIFICATE-----\nBBBB\n-----END CERTIFICATE-----",
                "usr/share/ca-certificates/mozilla/README": b"not a cert\n",
            })
            b2, n2 = assemble_ca_bundle(deb)
            check("assemble_ca_bundle finds 2 certs", n2 == 2)
            check("assemble_ca_bundle ignores non-cert README",
                  b"not a cert" not in b2)
            check("assemble_ca_bundle newline-terminates each cert",
                  b2.endswith(b"-----END CERTIFICATE-----\n"))
            check("assemble_ca_bundle sorts by path (A before B)",
                  b2.index(b"AAAA") < b2.index(b"BBBB"))

        # --- locale group from a synthetic libc-bin-like .deb -------------- #
        with tempfile.TemporaryDirectory() as t:
            tmp = Path(t)
            deb = _make_synthetic_deb(tmp, "synthetic-libc-bin.deb", {
                "usr/lib/locale/C.utf8/LC_CTYPE": b"CTYPE-DATA",
                "usr/lib/locale/C.utf8/LC_MESSAGES/SYS_LC_MESSAGES": b"MSG",
                "usr/bin/iconv": b"\x7fELF-unrelated",   # must NOT be packed
            })
            idx = {"libc-bin": {"Filename": "pool/x/libc-bin.deb"}}
            out = tmp / "loc.tar"
            # point the download at the local file by pre-seeding the cache name.
            cache = tmp / "cache"
            cache.mkdir()
            shutil.copy(deb, cache / "libc-bin.deb")
            res = build_common_data_overlay(
                out, ["locale"], index=idx, cache_dir=cache)
            with tarfile.open(out) as tar:
                names = {m.name for m in tar.getmembers()}
            check("locale overlay ships C.utf8/LC_CTYPE",
                  "./usr/lib/locale/C.utf8/LC_CTYPE" in names)
            check("locale overlay ships nested LC_MESSAGES file",
                  "./usr/lib/locale/C.utf8/LC_MESSAGES/SYS_LC_MESSAGES" in names)
            check("locale overlay does NOT pack unrelated usr/bin/iconv",
                  "./usr/bin/iconv" not in names)
            check("locale file_count == 2", res.locale_file_count == 2)
    else:
        check("ar available for deb-based selftests (skipped)", True)

    # --- §5-E conformance of a built overlay ------------------------------- #
    try:
        from tools.stage_tar_spec import validate_stage_tar
        with tempfile.TemporaryDirectory() as t:
            out = Path(t) / "conf.tar"
            build_common_data_overlay(
                out, ["ca", "machine-id"], ca_bundle=bundle, ca_cert_count=3)
            rep = validate_stage_tar(str(out))
            check("built overlay is stage_tar_spec conformant", rep.conformant)
    except Exception as exc:  # pragma: no cover
        check(f"stage_tar_spec cross-check ({exc!r})", False)

    print(f"\nselftest: {'ALL PASS' if failures == 0 else str(failures) + ' FAILED'}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
